using System;
using System.Collections.Generic;
using System.Linq;
using Avalonia; // DevToolsExtensions.AttachDevTools (Debug builds only)
using Avalonia.Controls;
using Avalonia.Controls.Primitives; // PlacementMode, for the Res menu
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using R5Flowstate.Linux.Core;
using R5Flowstate.Shell.Linux.ViewModels;

namespace R5Flowstate.Shell.Linux.Views;

public partial class MainWindow : Window
{
    private MainViewModel Vm => (MainViewModel)DataContext!;

    public MainWindow()
    {
        // Generated by the Avalonia name generator: loads the XAML and then
        // assigns every x:Name field via FindControl. Don't hand-roll this —
        // a custom InitializeComponent shadows it and leaves the fields null.
        InitializeComponent();
        DataContext = new MainViewModel();
        // The notice version lives here, so the browser asks this window before
        // it lists anything (MasterServerClient is never called for a locked tab).
        Vm.ServersUnlockedProbe = ServersUnlocked;
        AttachInstallGate();
        AttachInstallProgress();
        AttachLeaderboards();
        AttachBlog();
        AttachConsole();

#if DEBUG
        // F12 opens the visual/logical tree inspector. The headless selftest run
        // has no windowing backend to host it, so it is skipped there.
        if (!Program.SelfTest)
        {
            this.AttachDevTools();
        }
#endif
    }

    /// <summary>Windows' <c>_windowClosing</c>: the host heartbeat's ping is a
    /// background task that lands on the dispatcher, and a launcher that is
    /// going away must not be told about a server it can no longer warn anyone
    /// about.</summary>
    protected override void OnClosing(WindowClosingEventArgs e)
    {
        Vm.WindowClosing = true;
        base.OnClosing(e);
    }

    /// <summary>The watchdog's tick source, as the suite finds it: Windows'
    /// two-second process watch, which the heartbeat rides.</summary>
    internal bool ProcWatchRunning => _procWatch?.IsEnabled == true;

    /// <summary>Upstream's PaintInstallControls, in the part this port still has to
    /// do by hand: whether the *play* tab's bar is on screen.
    ///
    /// <para>Everything inside the setup card is bound (the idle form and the
    /// progress card swap on <c>Installing</c>, and the card's own bar is
    /// <c>InstallFraction</c>), so nothing here writes to those — a local set on a
    /// bound property replaces the binding, which is exactly how upstream loses its
    /// <c>{loc:T}</c> title the first time this method runs. The one control that
    /// cannot be bound on its own is <c>BarSimpleInstall</c>: it takes its
    /// visibility from the fraction *and* from whether the setup card is up, and
    /// that second question is the view's.</para>
    /// </summary>
    private void PaintInstallControls()
    {
        if (BarSimpleInstall is null) return;
        var busy = Vm.Installing;
        // The setup card carries a bar of its own while a job runs, so the play
        // tab's bar is for the other case: verifying or repairing an install that
        // is already there.
        BarSimpleInstall.IsVisible = busy && !PanelSimpleSetup.IsVisible;
        if (!busy) BarSimpleInstall.Value = 0;
    }

    /// <summary>Keeps the install chrome in step with the view model: the play
    /// tab's bar, and the install gate, which has to be re-asked when a job ends
    /// because that is when the game can have started existing.</summary>
    private void AttachInstallProgress()
    {
        Vm.PropertyChanged += (_, e) =>
        {
            if (e.PropertyName == nameof(MainViewModel.Installing))
            {
                AttachInstallGate();
                PaintInstallControls();
            }
        };
        PaintInstallControls();
    }

    private void AttachInstallGate()
    {
        // Mirrors the Windows launcher's ShowSimpleSetupLayout: the setup card
        // replaces the play panel *and its action bar* while the install is
        // missing, the tab is relabelled once the install exists, and the server
        // browser stays locked until then.
        //
        // "The install is missing" is asked through InstallPresence rather than
        // LooksLikeInstall, because a root with the platform lane and no game
        // satisfies Windows' marker rule (the platform ships its own client.dll)
        // and would hide the one card that can install the game. See
        // InstallPresence.
        var setup = !InstallPresence.GamePresent(Vm.InstallPath);
        PanelSimpleSetup.IsVisible = setup;
        PanelSimplePlay.IsVisible = !setup;
        PanelSimplePlayOptions.IsVisible = !setup;
        // The bar carries PLAY / CHANGE MAP, neither of which is meaningful
        // before there is an install — the setup card owns the CTA.
        BarSimplePlay.IsVisible = !setup;
        BtnTabLocal.Content = Loc.Get(setup ? "tab_install" : "tab_play_local");
        BtnTabServers.IsEnabled = !setup;
        BtnTabServers.Opacity = setup ? 0.4 : 1;
        BtnTabServers.SetValue(ToolTip.TipProperty, Loc.Get(
            setup ? "tip_servers_locked"
                  : ServersUnlocked() ? "tip_browse_servers" : "status_eula_servers"));
        // The size line must resolve to a real state (measured, or "size
        // unknown") rather than sitting on the checking placeholder.
        _ = Vm.RefreshInstallSizeAsync();
        // And the install's playlists are read here too, because whether they
        // exist is part of what "the install is present" means: Windows reloads
        // its catalog at exactly these points (startup and an install change).
        _ = Vm.ReloadCatalogAsync();
        // The Local tab is the one that opens, and it owns no browser line — nor
        // the header Refresh button, which belongs to Servers/Leaderboards/Blog.
        TxtBrowserStatus.IsVisible = false;
        BtnBrowserRefresh.IsVisible = false;
    }

    // ------------------------------------------------------------- chrome

    private void OnCaptionPointerPressed(object? sender, PointerPressedEventArgs e)
    {
        if (e.ClickCount == 2)
        {
            ToggleMaximize();
            e.Handled = true;
            return;
        }
        if (e.GetCurrentPoint(this).Properties.IsLeftButtonPressed)
            BeginMoveDrag(e);
    }

    private void ToggleMaximize()
    {
        WindowState = WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
        // Swap the square glyph for a restore glyph, like the Windows template.
        TxtWinMaxGlyph.Data = WindowState == WindowState.Maximized
            ? Geometry.Parse("M 3 1 L 3 9 M 3 1 L 11 1 M 10 3 L 10 11 M 10 11 L 2 11")
            : Geometry.Parse("M 0 0 L 0 10 M 0 0 L 10 0 M 10 0 L 10 10 M 0 10 L 10 10");
    }

    private void OnWinMinimize(object? sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;
    private void OnWinMaximize(object? sender, RoutedEventArgs e) => ToggleMaximize();
    private void OnWinClose(object? sender, RoutedEventArgs e) => Close();

    private void OnModeToggle(object? sender, RoutedEventArgs e)
    {
        Vm.IsSimpleMode = !Vm.IsSimpleMode;
        Vm.AppendLog(Vm.IsSimpleMode ? "Switched to player layout." : "Switched to advanced developer layout.");
    }

    // --------------------------------------------------------------- tabs

    private void SetSimpleTab(Button? tab, Control panel)
    {
        foreach (var b in new[]
                 {
                     BtnTabLocal, BtnTabServers, BtnTabLeaderboards, BtnTabConsole, BtnTabMods,
                     BtnTabBlog, BtnTabNotes, BtnTabCredits,
                 })
        {
            b.Classes.Remove("on");
        }
        foreach (var p in new[]
                 {
                     PanelSimpleLocal, PanelSimpleServers, PanelSimpleLeaderboards, PanelSimpleConsole,
                     PanelSimpleMods, PanelSimpleBlog, PanelSimpleNotes, PanelSimpleCredits,
                     (Control)PanelSimpleSettings,
                 })
        {
            p.IsVisible = false;
        }
        tab?.Classes.Add("on");
        panel.IsVisible = true;

        // The browser's line belongs to the Servers tab (Windows toggles the same
        // TextBlock in ApplySimpleTab), and the 12 s poll only runs while that tab
        // is the visible one — a hidden tab has no business on the network.
        var servers = ReferenceEquals(panel, PanelSimpleServers);
        TxtBrowserStatus.IsVisible = servers;
        if (servers)
            StartBrowserPoll();
        else
            StopBrowserPoll();

        // Same rule for the leaderboards: the 30 s board poll and the 15 s
        // activity poll only run while that tab is the visible one. (Windows
        // leaves the activity timer up on every tab, but its only consumer is a
        // line inside this panel, so stopping it off-tab costs nothing visible
        // and saves a request every 15 s.)
        if (ReferenceEquals(panel, PanelSimpleLeaderboards))
            StartLeaderboardPoll();
        else
            StopLeaderboardPoll();

        // Windows parity (ApplySimpleTab): the header Refresh button belongs to
        // the three networked tabs and says what it will refresh, and it is the
        // tab's own refresh rather than always the server list.
        var blog = ReferenceEquals(panel, PanelSimpleBlog);
        BtnBrowserRefresh.IsVisible = servers || ReferenceEquals(panel, PanelSimpleLeaderboards) || blog;
        BtnBrowserRefresh.SetValue(ToolTip.TipProperty, Loc.Get(
            ReferenceEquals(panel, PanelSimpleLeaderboards) ? "tip_refresh_lb"
            : blog ? "tip_refresh_blog"
            : "tip_refresh_servers"));

        // The blog's own two concerns: the unread dot is stamped while the tab
        // is up (SyncBlogTab in Windows), and the list comes back scrolled to
        // the top whenever the tab is entered.
        Vm.SetBlogTabShown(blog);
        if (blog && PanelBlogList.IsVisible)
            ScrollBlogList.ScrollToHome();

        // The console's chrome follows the tab: Stop is only offered while the
        // console is the pane in front of the player (RefreshConsoleChrome).
        if (DataContext is not null)
            RefreshConsoleChrome();
    }

    /// <summary>Windows parity: OnBrowserRefresh — the one button refreshes
    /// whichever of the networked tabs is up.</summary>
    private void OnHeaderRefresh(object? sender, RoutedEventArgs e)
    {
        if (PanelSimpleLeaderboards.IsVisible)
            Vm.RefreshLeaderboardsCommand.Execute(null);
        else if (PanelSimpleBlog.IsVisible)
            Vm.RefreshBlogCommand.Execute(null);
        else
            Vm.RefreshServersCommand.Execute(null);
    }

    private void OnSimpleTabLocal(object? sender, RoutedEventArgs e) =>
        SetSimpleTab(BtnTabLocal, PanelSimpleLocal);
    private async void OnSimpleTabServers(object? sender, RoutedEventArgs e)
    {
        // Windows parity: the master-server list is gated behind the legal
        // notice. Fetch (or reuse) the notice, and only switch to the tab once
        // it is accepted — declining keeps the player where they were.
        if (!await EnsureEulaAcceptedAsync())
            return;
        SetSimpleTab(BtnTabServers, PanelSimpleServers);
        Vm.RefreshServersCommand.Execute(null);
    }
    private void OnSimpleTabLeaderboards(object? sender, RoutedEventArgs e)
    {
        SetSimpleTab(BtnTabLeaderboards, PanelSimpleLeaderboards);
        // Windows refreshes on tab open (not just the quiet poll).
        Vm.RefreshLeaderboardsCommand.Execute(null);
    }
    private void OnSimpleTabConsole(object? sender, RoutedEventArgs e) =>
        SetSimpleTab(BtnTabConsole, PanelSimpleConsole);
    private void OnSimpleTabMods(object? sender, RoutedEventArgs e) =>
        SetSimpleTab(BtnTabMods, PanelSimpleMods);
    private void OnSimpleTabBlog(object? sender, RoutedEventArgs e)
    {
        SetSimpleTab(BtnTabBlog, PanelSimpleBlog);
        // Windows refreshes on tab open (the feed is the only writer of the
        // unread dot, so an entrance is also the moment it gets re-stamped).
        Vm.RefreshBlogCommand.Execute(null);
    }
    private void OnSimpleTabNotes(object? sender, RoutedEventArgs e)
    {
        SetSimpleTab(BtnTabNotes, PanelSimpleNotes);
        // Opening the tab is what marks the notes read (and clears the dot).
        Vm.EnterNotesTab();
    }
    private void OnSimpleTabCredits(object? sender, RoutedEventArgs e) =>
        SetSimpleTab(BtnTabCredits, PanelSimpleCredits);
    private void OnSimpleTabSettings(object? sender, RoutedEventArgs e) =>
        SetSimpleTab(sender as Button, PanelSimpleSettings);

    private void UpdateTabScrollButtons()
    {
        var sv = TabScroll;
        BtnTabScrollLeft.IsVisible = sv.Offset.X > 1;
        BtnTabScrollRight.IsVisible = sv.Offset.X < sv.Extent.Width - sv.Viewport.Width - 1;
    }

    private void OnTabScrollLeft(object? sender, RoutedEventArgs e)
    {
        TabScroll.Offset = TabScroll.Offset.WithX(Math.Max(0, TabScroll.Offset.X - 240));
        UpdateTabScrollButtons();
    }

    private void OnTabScrollRight(object? sender, RoutedEventArgs e)
    {
        TabScroll.Offset = TabScroll.Offset.WithX(Math.Min(TabScroll.Extent.Width, TabScroll.Offset.X + 240));
        UpdateTabScrollButtons();
    }

    // ------------------------------------------------------------ play panel

    private void OnLaunchArgsClick(object? sender, RoutedEventArgs e) =>
        SetSimpleTab(null, PanelSimpleSettings);

    /// <summary>Windows' OnChangeMap: send the selected pair to the live level.
    /// The map *picker* is its own control here and on Windows
    /// (<c>OnToggleMapPicker</c>), which is what this button used to do while
    /// there was no session to send to.</summary>
    private void OnChangeMap(object? sender, RoutedEventArgs e) =>
        Vm.SendChangeMapCommand.Execute(null);

    private void OnToggleMapPicker(object? sender, RoutedEventArgs e)
    {
        PanelMapPicker.IsVisible = !PanelMapPicker.IsVisible;
        // Windows' EnsureMapTiles runs on the open, not on the grid rebuild: the
        // thumbnails are only worth decoding once someone is looking at them.
        if (PanelMapPicker.IsVisible)
            Vm.EnsureMapTiles();
    }

    private void OnMapTileClick(object? sender, RoutedEventArgs e)
    {
        if (sender is Button { DataContext: MapTileVM tile })
        {
            Vm.SelectMapCommand.Execute(tile);
            PanelMapPicker.IsVisible = false;
        }
    }

    private void OnModeChipClick(object? sender, RoutedEventArgs e)
    {
        if (sender is Button { DataContext: ModeItemVM mode })
            Vm.SelectModeCommand.Execute(mode);
    }

    /// <summary>
    /// Windows' OnReloadLoadscreen: shuffle the hero through the install's
    /// standalone art loadscreens. It is the lobby's button there, and only the
    /// lobby's, because the lobby is the one mode whose own pak is a stub.
    /// </summary>
    private void OnReloadLoadscreen(object? sender, RoutedEventArgs e)
    {
        if (string.IsNullOrWhiteSpace(Vm.InstallPath))
        {
            Vm.AppendLog("Loadscreen shuffle: no install folder set — the hero keeps the accent gradient.");
            return;
        }
        Vm.RerollLoadscreen();
    }

    /// <summary>
    /// Windows' OnResolutionPresetClick: build the menu from what the session lists
    /// and open it. Built per click rather than cached, because the modes a display
    /// offers can change while the launcher is open — a monitor plugged in, a KDE
    /// resolution change — and a stale menu is one that offers a size that is no
    /// longer there. The build reads an enumeration that is already cached, so it
    /// costs nothing per click.
    ///
    /// Three sections, upstream's order: the window modes as a radio group, a
    /// separator, then "Game default" and one submenu per aspect group. Avalonia's
    /// <see cref="MenuItemToggleType.Radio"/> is what keeps two modes from being
    /// ticked at once — Windows hand-rolls that with SyncWindowModeChecks because WPF
    /// has no radio menu item.
    /// </summary>
    private void OnResolutionPresetClick(object? sender, RoutedEventArgs e)
    {
        if (sender is not Button target)
            return;

        var menu = new ContextMenu { Placement = PlacementMode.Top };
        menu.Classes.Add(ResMenuClass);

        foreach (var mode in DisplayModes.WindowModes)
        {
            var item = new MenuItem
            {
                Header = Loc.Get(DisplayModes.LocKey(mode)),
                Tag = mode,
                ToggleType = MenuItemToggleType.Radio,
                GroupName = "r5f-window-mode",
                IsChecked = mode == Vm.ClientWindowMode,
            };
            item.Classes.Add(ResMenuClass);
            item.Click += OnWindowModePicked;
            menu.Items.Add(item);
        }

        var separator = new Separator();
        separator.Classes.Add(ResMenuClass);
        menu.Items.Add(separator);

        // The one entry Windows has no equivalent of: this port treats 0x0 as "no
        // override", which is the only way back to the game's own choice once a size
        // has been picked.
        var gameDefault = new MenuItem
        {
            Header = Loc.Get("resolution_game_default"),
            Tag = new DisplayModes.DisplayMode(0, 0),
        };
        gameDefault.Classes.Add(ResMenuClass);
        gameDefault.Click += OnResolutionPresetPicked;
        menu.Items.Add(gameDefault);

        foreach (var group in DisplayModes.Groups())
        {
            var header = new MenuItem { Header = group.Caption };
            header.Classes.Add(ResMenuClass);

            foreach (var preset in group.Modes)
            {
                var item = new MenuItem
                {
                    Header = DisplayModes.Label(preset),
                    Tag = preset,
                };
                item.Classes.Add(ResMenuClass);
                item.Click += OnResolutionPresetPicked;
                header.Items.Add(item);
            }

            menu.Items.Add(header);
        }

        // The class has to be on every item, not just on the menu: a MenuItem built
        // here is not a child of the ContextMenu, and the submenu's items are not
        // children of the group header. The theme's selectors are scoped by it
        // (ContextMenu.resmenu / MenuItem.resmenu / Separator.resmenu), which is why
        // upstream's per-group ItemContainerStyle restatement has no equivalent here.
        target.ContextMenu = menu;
        menu.Open(target);
    }

    /// <summary>The class the Res menu and its items carry; see the theme's MENUS
    /// section.</summary>
    const string ResMenuClass = "resmenu";

    private void OnWindowModePicked(object? sender, RoutedEventArgs e)
    {
        if (sender is MenuItem { Tag: string mode })
            Vm.SetClientWindowMode(mode);
    }

    private void OnResolutionPresetPicked(object? sender, RoutedEventArgs e)
    {
        if (sender is MenuItem { Tag: DisplayModes.DisplayMode mode })
            Vm.SetResolution(mode.Width, mode.Height);
    }

    /// <summary>
    /// A typed-in size, committed when the box loses focus (upstream's
    /// OnClientResolutionLostFocus). Reads the boxes rather than the view model,
    /// because the two-way binding is what carries a <em>parseable</em> number and
    /// nothing carries an unparseable one: "1e9" never reaches ClientWidth, so the
    /// box has to be told what the value actually is afterwards — which is what the
    /// write-back below does, for both good and refused input.
    /// </summary>
    private void OnClientResolutionLostFocus(object? sender, RoutedEventArgs e)
    {
        var w = ReadBox(TxtClientWidth, Vm.ClientWidth);
        var h = ReadBox(TxtClientHeight, Vm.ClientHeight);
        // Only when something actually changed. Tabbing from the width box to the
        // height box is a LostFocus too, and committing an unchanged pair would write
        // settings.json and add a log line for every focus change.
        if (w != Vm.ClientWidth || h != Vm.ClientHeight)
            Vm.SetResolution(w, h);

        // Both boxes, whichever one was left: the pair is what launches, so a size
        // that was refused has to snap back in both.
        TxtClientWidth.Text = Vm.ClientWidth.ToString();
        TxtClientHeight.Text = Vm.ClientHeight.ToString();
        // The Servers tab's twin boxes are bound to the same two properties, so they
        // follow on their own; the write-back above is only for the pair on screen.
    }

    static int ReadBox(TextBox box, int fallback)
        => int.TryParse(box.Text?.Trim(), out var value) ? value : fallback;

    // ------------------------------------------------------- legal notice gate

    private int _eulaVersionCurrent;
    private bool _eulaDialogOpen;

    /// <summary>Same endpoint the Windows build ships with (ProductConstants).</summary>
    private static string CurrentMasterServerUrl() => NoticeClient.DefaultMasterServerUrl;

    /// <summary>Windows parity: MainWindow.ServersUnlocked.</summary>
    private bool ServersUnlocked() =>
        MainViewModel.ServersUnlockedFor(Vm.EulaVersionAccepted, _eulaVersionCurrent);

    /// <summary>
    /// Shows the agreement before anything from the master server is listed.
    /// Returns true when the player has accepted the current notice version.
    /// </summary>
    private async System.Threading.Tasks.Task<bool> EnsureEulaAcceptedAsync()
    {
        if (_eulaDialogOpen)
            return false;

        // Already accepted at this session's known-current version: no round
        // trip. A server-side bump is picked up on the next launcher start.
        if (_eulaVersionCurrent > 0 && Vm.EulaVersionAccepted >= _eulaVersionCurrent)
            return true;

        var fetched = await NoticeClient.GetEulaAsync(CurrentMasterServerUrl(), Vm.EulaUiLanguage());
        if (!fetched.Success)
        {
            Vm.BrowserStatus = fetched.Error ?? Loc.Get("status_eula_failed");
            Vm.SimpleStatus = Loc.Get("status_eula_failed_retry");
            Vm.AppendLog("Legal notice fetch failed: " + (fetched.Error ?? "unknown error"));
            return false;
        }

        _eulaVersionCurrent = fetched.Version > 0 ? fetched.Version : 1;
        if (Vm.EulaVersionAccepted >= _eulaVersionCurrent)
            return true;

        _eulaDialogOpen = true;
        try
        {
            var dlg = new EulaWindow(this, CurrentMasterServerUrl(), requireAccept: true,
                prefetched: fetched, vm: Vm);
            var ok = await dlg.ShowDialog<bool>(this);
            if (!ok || !dlg.Accepted)
            {
                Vm.BrowserStatus = Loc.Get("status_eula_servers");
                Vm.SimpleStatus = Loc.Get("status_eula_servers");
                Vm.AppendLog("Legal notice declined — the Servers tab stays locked.");
                return false;
            }
            Vm.SaveEulaAccepted(dlg.AcceptedVersion);
            _eulaVersionCurrent = dlg.AcceptedVersion;
            Vm.AppendLog($"Legal notice v{dlg.AcceptedVersion} accepted ({fetched.Lang}).");
            return true;
        }
        finally
        {
            _eulaDialogOpen = false;
        }
    }

    // ------------------------------------------------------------- servers

    /// <summary>The browser's own refresh cadence, same 12 s as the Windows
    /// launcher. Owned by the window because visibility is a window fact: the
    /// timer runs only while the Servers tab is the visible one.</summary>
    private Avalonia.Threading.DispatcherTimer? _browserTimer;

    private void StartBrowserPoll()
    {
        // A tab with no install behind it has nothing to list (the tab itself is
        // disabled in that state, so this is the belt to that braces).
        if (!ServersUnlocked() || !InstallPresence.GamePresent(Vm.InstallPath))
        {
            StopBrowserPoll();
            return;
        }

        if (_browserTimer is null)
        {
            _browserTimer = new Avalonia.Threading.DispatcherTimer
            {
                Interval = TimeSpan.FromSeconds(12),
            };
            _browserTimer.Tick += OnBrowserTick;
        }
        if (!_browserTimer.IsEnabled)
            _browserTimer.Start();
    }

    private void StopBrowserPoll() => _browserTimer?.Stop();

    private async void OnBrowserTick(object? sender, EventArgs e)
    {
        if (!ServersUnlocked())
        {
            StopBrowserPoll();
            return;
        }
        // Quiet: the same fetch the refresh button makes, without repainting the
        // status line to "Refreshing…" every 12 s.
        await Vm.PollServersAsync();
    }

    private void OnJoinServerClick(object? sender, RoutedEventArgs e)
    {
        if (sender is Button { DataContext: ServerRowVM row })
            Vm.JoinServerRowCommand.Execute(row);
    }

    private void OnToggleFavorite(object? sender, RoutedEventArgs e)
    {
        if (sender is Button { DataContext: ServerRowVM row })
            Vm.ToggleFavoriteCommand.Execute(row);
    }

    private void OnToggleServersClientOptions(object? sender, RoutedEventArgs e) =>
        PanelServersClientOptions.IsVisible = !PanelServersClientOptions.IsVisible;

    // ----------------------------------------------------------- leaderboards

    // The sixteen column headers, in the same order as the table and its grid.
    private Button[] LbHeaderButtons() => new[]
    {
        BtnLbColRank, BtnLbColPlayer, BtnLbColScore, BtnLbColK, BtnLbColD, BtnLbColKd,
        BtnLbColDmg, BtnLbColAcc, BtnLbColWpn, BtnLbColIn, BtnLbColHs, BtnLbColHits,
        BtnLbColWins, BtnLbColGames, BtnLbColWr, BtnLbColStreak,
    };

    private void AttachLeaderboards()
    {
        // The sort state and the view (board vs history) live in the view model;
        // the window only paints them, so both are driven by events rather than
        // by the view model reaching into controls.
        Vm.LbSortChanged += PaintLbHeaders;
        Vm.LbViewChanged += ApplyLbView;
        PaintLbHeaders();
        ApplyLbView();
    }

    /// <summary>Windows parity: PaintLbSortHeaders — the caption plus ▲/▼ on the
    /// column that is sorting, and the accent colour on that column.</summary>
    private void PaintLbHeaders()
    {
        foreach (var btn in LbHeaderButtons())
        {
            var key = btn.Tag as string ?? "";
            btn.Content = Vm.LbHeaderCaption(key);
            btn.Foreground = Vm.LbHeaderIsActive(key)
                ? ThemeBrushes.AccentBright
                : ThemeBrushes.TextMuted;
        }
    }

    /// <summary>Windows parity: ShowLbBoardView / ShowLbHistoryView.</summary>
    private void ApplyLbView()
    {
        var history = Vm.LbViewHistory;
        ScrollLbBoard.IsVisible = !history;
        ScrollLbHistory.IsVisible = history;
        if (history)
        {
            BtnLbViewBoard.Classes.Remove("on");
            BtnLbViewMatches.Classes.Add("on");
        }
        else
        {
            BtnLbViewBoard.Classes.Add("on");
            BtnLbViewMatches.Classes.Remove("on");
        }
    }

    private void OnLbSortClick(object? sender, RoutedEventArgs e)
    {
        if (sender is Control { Tag: string key })
            Vm.LbSortCommand.Execute(key);
    }

    private void OnLbViewBoard(object? sender, RoutedEventArgs e) =>
        Vm.LbShowBoardCommand.Execute(null);

    private void OnLbViewMatches(object? sender, RoutedEventArgs e) =>
        Vm.LbShowHistoryCommand.Execute(null);

    private void OnLbSeasonChanged(object? sender, SelectionChangedEventArgs e)
    {
        // Rebuilding the list resets SelectedItem, which lands here too — the
        // command ignores a season that is already in force.
        if (sender is ComboBox { SelectedItem: LbSeasonVM season })
            Vm.LbSeasonChangedCommand.Execute(season);
    }

    // 400 ms debounce, as Windows does: typing a name must not fire one request
    // per keystroke.
    private Avalonia.Threading.DispatcherTimer? _lbSearchTimer;

    private void OnLbSearchTextChanged(object? sender, TextChangedEventArgs e)
    {
        _lbSearchTimer ??= new Avalonia.Threading.DispatcherTimer
        {
            Interval = TimeSpan.FromMilliseconds(400),
        };
        _lbSearchTimer.Tick -= OnLbSearchDebounced;
        _lbSearchTimer.Tick += OnLbSearchDebounced;
        _lbSearchTimer.Stop();
        _lbSearchTimer.Start();
    }

    private void OnLbSearchDebounced(object? sender, EventArgs e)
    {
        _lbSearchTimer?.Stop();
        Vm.LbSearchCommand.Execute(TxtLbSearch.Text);
    }

    private void OnLbSearchKeyDown(object? sender, KeyEventArgs e)
    {
        if (e.Key != Key.Enter)
            return;
        e.Handled = true;
        _lbSearchTimer?.Stop();
        Vm.LbSearchCommand.Execute(TxtLbSearch.Text);
    }

    private void OnLeaderboardRowClick(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (sender is Control { DataContext: LeaderboardRowVM row })
            Vm.LbSelectRowCommand.Execute(row);
    }

    private void OnLbHistoryRowClick(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (sender is Control { DataContext: MatchSessionVM row })
        {
            e.Handled = true;
            Vm.LbOpenMatchCommand.Execute(row);
        }
    }

    private void OnLbRecentMatchClick(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (sender is Control { DataContext: RecentMatchVM row })
        {
            e.Handled = true;
            Vm.LbOpenRecentMatchCommand.Execute(row);
        }
    }

    private void OnLbMatchPlayerClick(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (sender is Control { DataContext: MatchPlayerVM row })
        {
            e.Handled = true;
            Vm.LbOpenMatchPlayerCommand.Execute(row);
        }
    }

    /// <summary>The dimmed backdrop closes the match card; a click inside the card
    /// itself does not (Windows: OnMatchOverlayBackdropClick).</summary>
    private void OnLbMatchBackdropTapped(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (!ReferenceEquals(e.Source, sender))
            return;
        e.Handled = true;
        Vm.LbCloseMatchCommand.Execute(null);
    }

    /// <summary>Esc closes the match card first, then the player card. The
    /// console's own keys follow (Windows' OnWindowPreviewKeyDown): Ctrl+F opens
    /// the find bar for the pane the player was last in, F3 steps, and Esc closes
    /// — but only while the console tab is the one in front of them.</summary>
    private void OnWindowKeyDown(object? sender, KeyEventArgs e)
    {
        if (e.Key == Key.Escape && Vm.HandleLeaderboardEscape())
        {
            e.Handled = true;
            return;
        }

        if (!PanelSimpleConsole.IsVisible || _consoleFind.Count == 0)
            return;

        if (e.Key == Key.F && e.KeyModifiers.HasFlag(KeyModifiers.Control))
        {
            OpenConsoleFind(null);
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F3)
        {
            if (ActiveConsoleFind() is { } stepping)
            {
                StepConsoleFind(stepping, e.KeyModifiers.HasFlag(KeyModifiers.Shift) ? -1 : 1);
                e.Handled = true;
            }

            return;
        }

        if (e.Key == Key.Escape && ActiveConsoleFind() is { } closing)
        {
            CloseConsoleFind(closing);
            e.Handled = true;
        }
    }

    private Avalonia.Threading.DispatcherTimer? _lbTimer;
    private Avalonia.Threading.DispatcherTimer? _lbActivityTimer;

    private void StartLeaderboardPoll()
    {
        if (_lbTimer is null)
        {
            _lbTimer = new Avalonia.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(30) };
            _lbTimer.Tick += OnLbTick;
        }
        if (_lbActivityTimer is null)
        {
            _lbActivityTimer = new Avalonia.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(15) };
            _lbActivityTimer.Tick += OnLbActivityTick;
        }
        if (!_lbTimer.IsEnabled)
            _lbTimer.Start();
        if (!_lbActivityTimer.IsEnabled)
            _lbActivityTimer.Start();
    }

    private void StopLeaderboardPoll()
    {
        _lbTimer?.Stop();
        _lbActivityTimer?.Stop();
    }

    private async void OnLbTick(object? sender, EventArgs e) =>
        await Vm.PollLeaderboardsAsync();

    private async void OnLbActivityTick(object? sender, EventArgs e) =>
        await Vm.PollActivityAsync();

    // ---------------------------------------------------------------- blog

    private void AttachBlog()
    {
        // The list and the reader are switched by the view model's state; the
        // window owns what only a view can do — scrolling a ScrollViewer, and
        // handing a cover URL to the image loader (which paints a control, and
        // returns to this thread to do it).
        Vm.BlogListShown += () => ScrollBlogList.ScrollToHome();
        Vm.BlogReaderPainted += () =>
        {
            BlogImageLoader.Bind(ImgBlogCover, Vm.BlogReaderCoverUri);
            ScrollBlogReader.ScrollToHome();
        };
        // Links inside a post follow the same path as every other external link
        // in the launcher (and are the one place a post's text can leave the app).
        BlogBody.OpenLink = Vm.OpenUrl;
    }

    private void OnBlogCardClick(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (sender is not Control { Tag: BlogPostRow row })
            return;
        e.Handled = true;
        _ = Vm.OpenBlogPostAsync(row.Slug);
    }

    /// <summary>Enter or Space opens the focused card — the same keys the
    /// Windows card handles, so the list is walkable from the keyboard.</summary>
    private void OnBlogCardKey(object? sender, KeyEventArgs e)
    {
        if (e.Key is not (Key.Enter or Key.Space))
            return;
        if (sender is not Control { Tag: BlogPostRow row })
            return;
        e.Handled = true;
        _ = Vm.OpenBlogPostAsync(row.Slug);
    }

    private void OnBlogBack(object? sender, RoutedEventArgs e) => Vm.ShowBlogList();

    private void OnBlogOpenSite(object? sender, RoutedEventArgs e)
    {
        var url = Vm.BlogSiteUrl();
        if (url.Length > 0)
            Vm.OpenUrl(url);
    }

    // ---------------------------------------------------------------- notes

    // The "on" class is bound to NotesShowLauncher in the XAML, so the page switch
    // is entirely VM state — same as the Windows launcher, which repaints from
    // ApplyNotesPage rather than from the click.
    private void OnNotesPageGame(object? sender, RoutedEventArgs e) => Vm.ShowNotesGame();

    private void OnNotesPageLauncher(object? sender, RoutedEventArgs e) => Vm.ShowNotesLauncher();

    // ---------------------------------------------------------------- mods

    private void SetModsSection(bool installed)
    {
        BtnModsSectionInstalled.Classes.Set(installed);
        BtnModsSectionBrowse.Classes.Set(!installed);
        PanelModsInstalled.IsVisible = installed;
        PanelModsBrowse.IsVisible = !installed;
    }

    private void OnModsSectionInstalled(object? sender, RoutedEventArgs e) => SetModsSection(true);
    private void OnModsSectionBrowse(object? sender, RoutedEventArgs e) => SetModsSection(false);

    private async void OnModsInstallFile(object? sender, RoutedEventArgs e)
    {
        var files = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
        {
            Title = "Select a mod package (.vpk / .zip)",
            AllowMultiple = false,
        });
        if (files.Count > 0)
            Vm.AppendLog($"Mod file picked: {files[0].Path} — the install step lands with the content installer.");
    }

    private async void OnModsImport(object? sender, RoutedEventArgs e)
    {
        var files = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
        {
            Title = "Import mods profile",
            AllowMultiple = false,
        });
        if (files.Count > 0)
            Vm.AppendLog($"Profile import: {files[0].Path} — profile import lands with the content installer.");
    }

    private void OnModsExport(object? sender, RoutedEventArgs e) =>
        Vm.AppendLog("Profile export lands with the content installer.");

    private void OnModUninstall(object? sender, RoutedEventArgs e) =>
        Vm.AppendLog("Mod uninstall lands with the content installer.");

    private void OnModMoveUp(object? sender, RoutedEventArgs e) =>
        Vm.AppendLog("Mod order change lands with the content installer (load order mirrors Windows).");

    private void OnModMoveDown(object? sender, RoutedEventArgs e) =>
        Vm.AppendLog("Mod order change lands with the content installer (load order mirrors Windows).");

    private void OnModEnabledChanged(object? sender, RoutedEventArgs e) =>
        Vm.AppendLog("Mod enable state persists once the content installer manages <install>/mods.");

    private void OnBrowseModInstall(object? sender, RoutedEventArgs e) =>
        Vm.AppendLog("Mod download lands with the content installer.");

    // ------------------------------------------------------------- console

    private DispatcherTimer? _consoleTimer;
    private DispatcherTimer? _procWatch;
    private readonly ConsoleHistoryNav _historyNavServer = new();
    private readonly ConsoleHistoryNav _historyNavClient = new();

    /// <summary>
    /// The console's two panes, and the timer that feeds them. Lines arrive on
    /// the tap's reader threads, so they queue in the view model and land here in
    /// batches — Windows' own arrangement, for the same reason: appending a line
    /// at a time relayouts the pane thousands of times over a boot.
    /// </summary>
    void AttachConsole()
    {
        Vm.ConsoleLineQueued += StartConsoleTimer;

        // Windows' two-second _procWatch, which is where its host heartbeat
        // ticks from (MainWindow.xaml.cs:498-504). It cannot ride the console
        // drain timer above: that one stops whenever nothing is printing, and a
        // server that has stopped printing is exactly the case the watchdog
        // exists for. The view model enforces the ten-second spacing, so this
        // interval only decides how promptly a due ping goes out.
        _procWatch = new DispatcherTimer(DispatcherPriority.Background)
        {
            Interval = TimeSpan.FromSeconds(2),
        };
        _procWatch.Tick += (_, _) => Vm.TickHostHeartbeat();
        _procWatch.Start();

        // A console appearing means a launch happened, which is where Windows
        // brings the tab forward; and the server pane's own rule (a browser join
        // has no dedi of ours) is read through the view model, so it is
        // re-applied whenever that answer can have changed.
        Vm.ConsoleAttached += _ => MaybeOpenConsoleForLaunch();
        Vm.PropertyChanged += (_, e) =>
        {
            if (e.PropertyName == nameof(MainViewModel.ConsoleServerPaneOpen))
                ApplyConsoleView();
            else if (e.PropertyName is nameof(MainViewModel.HostSteeringReady)
                     or nameof(MainViewModel.ChangeMapBusy))
                RefreshConsoleChrome();
        };

        Vm.ConsoleReset += role =>
        {
            var pane = PaneFor(role);
            pane.Follow = true;
            pane.ClearFindMatch();

            // A cleared pane has no matches, so an open bar's count goes back to
            // nothing rather than holding a number about lines that are gone
            // (Windows' ResetConsoleFind does the same from the clear path).
            foreach (var bar in _consoleFind)
            {
                if (bar.Role == role && bar.Open)
                    bar.Counter.Text = "";
            }
        };
        Vm.ConsoleNoted += (role, text) =>
        {
            // The pane's own voice is worth seeing even when the player is on
            // another tab, so a note brings the console forward only if the
            // console is already the tab in front of them.
            if (PanelSimpleConsole.IsVisible)
                PaneFor(role).PinToEnd();
            else
                Vm.AppendLog(text);
        };

        InitConsoleFind();

        _consoleTimer = new DispatcherTimer(DispatcherPriority.Background)
        {
            Interval = TimeSpan.FromMilliseconds(250),
        };
        _consoleTimer.Tick += (_, _) =>
        {
            var painted = 0;
            foreach (var role in new[] { LaunchRole.Dedicated, LaunchRole.Client })
            {
                var pane = PaneFor(role);
                painted += Vm.DrainConsole(role);

                // A pane whose find bar is open is following a match, not the
                // tail — pinning it would scroll the player off what they are
                // reading. Its counter is kept honest instead.
                if (!ConsoleFindHolds(pane) && pane.Follow && painted > 0)
                    pane.PinToEnd();
            }

            ConsoleFindTick();

            if (!Vm.HasPendingConsole)
            {
                _consoleTimer.Stop();
                // A line queued between the drain and the stop saw the timer
                // still enabled and did not restart it.
                if (Vm.HasPendingConsole)
                    _consoleTimer.Start();
            }
        };
    }

    ConsolePane PaneFor(LaunchRole role) =>
        role == LaunchRole.Dedicated ? TxtConsoleServer : TxtConsoleClient;

    /// <summary>
    /// Windows' ApplyConsoleView: a join to someone else's server runs no dedi
    /// of ours, so the server pane collapses rather than sitting there empty
    /// with a command line that reaches nothing.
    /// </summary>
    void ApplyConsoleView()
    {
        var server = Vm.ConsoleServerPaneOpen;
        PaneConsoleServer.IsVisible = server;
        GridConsole.RowDefinitions[0].Height =
            server ? new GridLength(1, GridUnitType.Star) : new GridLength(0);
        GridConsole.RowDefinitions[1].Height = new GridLength(server ? 10 : 0);
        GridConsole.RowDefinitions[2].Height = new GridLength(1, GridUnitType.Star);
    }

    /// <summary>
    /// Windows' RefreshConsoleChrome: the mode/map pickers are the Play tab's
    /// rail in combo form, and Reload is for a level this launcher is hosting —
    /// a browser join has nothing for any of them to point at.
    /// </summary>
    internal void RefreshConsoleChrome()
    {
        ApplyConsoleView();
        BtnConsoleAction.IsVisible = PanelSimpleConsole.IsVisible;

        var pickers = ConsolePickersOpen();
        var host = pickers && Vm.HostSteeringReady && Vm.ServerConsoleLive;

        CmbConsoleMode.IsVisible = pickers && Vm.ModeCards.Count > 0;
        CmbConsoleMode.IsEnabled = !Vm.ChangeMapBusy;
        CmbConsoleMap.IsVisible = pickers && ConsoleMapPickerOpen();
        CmbConsoleMap.IsEnabled = !Vm.ChangeMapBusy;
        BtnReloadLevel.IsVisible = host;
        BtnReloadLevel.IsEnabled = host && !Vm.ChangeMapBusy;

        BindConsolePickers();
    }

    /// <summary>Windows' ConsolePickersOpen: the console tab of a run that is
    /// not an install, over a server pane that exists.</summary>
    bool ConsolePickersOpen() =>
        PanelSimpleConsole.IsVisible && Vm.ConsoleServerPaneOpen && !Vm.InstallInFlight;

    /// <summary>Windows' ConsoleMapPickerOpen: a mode that has a map to choose
    /// and is not its own map.</summary>
    bool ConsoleMapPickerOpen()
    {
        var card = Vm.SelectedMode;
        return ConsolePickersOpen() && card is { MapIsPinned: false } && card.Maps.Count > 1;
    }

    /// <summary>
    /// Windows' BindConsoleMapPicker + BindConsoleModePicker: the combos show the
    /// selected card and its maps, and the guard is against re-entering the
    /// selection handlers that setting them fires.
    /// </summary>
    internal void BindConsolePickers()
    {
        var card = Vm.SelectedMode;
        if (card is null)
            return;

        _suppressConsolePicker = true;
        try
        {
            if (!ReferenceEquals(CmbConsoleMode.ItemsSource, Vm.ModeCards)
                || CmbConsoleMode.ItemCount != Vm.ModeCards.Count
                || !ReferenceEquals(CmbConsoleMode.SelectedItem, card))
            {
                CmbConsoleMode.ItemsSource = null;
                CmbConsoleMode.ItemsSource = Vm.ModeCards;
                CmbConsoleMode.SelectedItem = card;
            }

            if (!ReferenceEquals(CmbConsoleMap.ItemsSource, card.Maps)
                || !ReferenceEquals(CmbConsoleMap.SelectedItem, card.SelectedMap))
            {
                CmbConsoleMap.ItemsSource = card.Maps;
                CmbConsoleMap.SelectedItem = card.SelectedMap;
            }
        }
        finally
        {
            _suppressConsolePicker = false;
        }
    }

    bool _suppressConsolePicker;

    /// <summary>Windows' OnConsoleModeSelectionChanged: picking a mode here is
    /// picking it in the rail — one card, one selection.</summary>
    private void OnConsoleModeSelectionChanged(object? sender, SelectionChangedEventArgs e)
    {
        if (_suppressConsolePicker)
            return;
        if (CmbConsoleMode.SelectedItem is ModeCardViewModel card)
            Vm.SelectModeCard(card, persist: true);
    }

    /// <summary>Windows' OnConsoleMapSelectionChanged: the mode keeps the map,
    /// and the hero follows.</summary>
    private void OnConsoleMapSelectionChanged(object? sender, SelectionChangedEventArgs e)
    {
        if (_suppressConsolePicker || Vm.SelectedMode is null)
            return;
        if (CmbConsoleMap.SelectedItem is MapOption opt)
        {
            Vm.SelectedMode.SelectedMap = opt;
            Vm.PersistModeSettings();
            Vm.RefreshHero();
        }
    }

    // --------------------------------------------------------- console find

    /// <summary>
    /// One pane's find bar. Windows holds the pane's <c>RichTextBox</c> and its
    /// WPF match ranges here; the port holds the pane control and leaves the
    /// matches in the view model (they are line/offset pairs, and the suite can
    /// read them back). Windows identifies a bar's pane through each control's
    /// <c>Tag</c>; so does this one — the tags say "Server"/"Client" rather than
    /// carrying the control, because a XAML <c>Tag</c> cannot name a sibling
    /// control here.
    /// </summary>
    sealed class ConsoleFindBar
    {
        public LaunchRole Role;
        public ConsolePane Pane = null!;
        public Control Bar = null!;
        public TextBox Input = null!;
        public TextBlock Counter = null!;
        public CheckBox CaseToggle = null!;
        public bool Open;

        /// <summary>
        /// Where the player is, as a line, so a rebuild caused by arriving output
        /// keeps them where they were instead of jumping to the oldest match.
        ///
        /// Following the tail wins over the current match, and has to: a
        /// following pane is looking at the newest lines, and its current match
        /// is by definition an older one — anchoring on it would pin the find to
        /// the match it first landed on while the log runs away underneath. Only
        /// a player who has scrolled away is anchored where they are standing.
        /// </summary>
        internal int Anchor(MainViewModel vm)
        {
            if (Pane.Follow)
                return MainViewModel.ConsoleFindTailAnchor;

            var i = vm.FindCurrent(Role);
            var matches = vm.FindMatches(Role);
            return i >= 0 && i < matches.Count ? matches[i].Line : 0;
        }
    }

    readonly List<ConsoleFindBar> _consoleFind = new();
    ConsoleFindBar? _findTarget;
    ConsoleFindBar? _findPendingQuery;
    DispatcherTimer? _findDebounce;
    int _findTick;

    /// <summary>Windows' InitConsoleFind: one bar per pane, the debounce timer,
    /// and the same control wiring (focus in either the pane or its command box
    /// makes that pane the find target).</summary>
    void InitConsoleFind()
    {
        if (_consoleFind.Count > 0)
            return;

        AddConsoleFindBar(LaunchRole.Dedicated, TxtConsoleServer, BarFindServer,
            TxtFindServer, TxtFindServerCount, ChkFindServerCase, TxtConsoleServerCmd);
        AddConsoleFindBar(LaunchRole.Client, TxtConsoleClient, BarFindClient,
            TxtFindClient, TxtFindClientCount, ChkFindClientCase, TxtConsoleClientCmd);
        _findTarget = _consoleFind.FirstOrDefault();

        _findDebounce = new DispatcherTimer(DispatcherPriority.Background)
        {
            Interval = TimeSpan.FromMilliseconds(150),
        };
        _findDebounce.Tick += (_, _) =>
        {
            _findDebounce!.Stop();
            var bar = _findPendingQuery;
            _findPendingQuery = null;
            if (bar is not null)
                RebuildConsoleFind(bar, jump: true);
        };
    }

    void AddConsoleFindBar(LaunchRole role, ConsolePane? pane, Control? bar,
        TextBox? input, TextBlock? counter, CheckBox? caseToggle, TextBox? cmd)
    {
        if (pane is null || bar is null || input is null || counter is null || caseToggle is null)
            return;

        var find = new ConsoleFindBar
        {
            Role = role,
            Pane = pane,
            Bar = bar,
            Input = input,
            Counter = counter,
            CaseToggle = caseToggle,
        };
        _consoleFind.Add(find);

        pane.GotFocus += (_, _) => _findTarget = find;

        // A press anywhere in the pane aims the find bar at it. Tunneled, not
        // bubbled: the pane is full of text controls that mark a press handled,
        // and the player's press is still a press on the pane.
        pane.AddHandler(InputElement.PointerPressedEvent,
            (_, _) => _findTarget = find, RoutingStrategies.Tunnel);
        pane.AddHandler(InputElement.PointerPressedEvent,
            (_, _) => _findTarget = find, RoutingStrategies.Bubble, handledEventsToo: true);
        input.GotFocus += (_, _) => _findTarget = find;
        if (cmd is not null)
            cmd.GotFocus += (_, _) => _findTarget = find;
    }

    /// <summary>Every find control carries its own pane's role in Tag.</summary>
    ConsoleFindBar? FindBarOf(object? sender) =>
        sender is Control { Tag: string tag }
            ? _consoleFind.FirstOrDefault(b => b.Role == ParseTag(tag))
            : null;

    /// <summary>
    /// The tags say "Server"/"Client" — the words on the tabs, matching the
    /// console command boxes — while the roles are Dedicated/Client. The server
    /// pane is the dedicated one.
    /// </summary>
    static LaunchRole ParseTag(string tag) =>
        tag == "Client" ? LaunchRole.Client : LaunchRole.Dedicated;

    ConsoleFindBar? ActiveConsoleFind() =>
        _findTarget is { Open: true } ? _findTarget
        : _consoleFind.FirstOrDefault(b => b.Open);

    /// <summary>True while a pane's bar is open. Windows' ConsoleFindHolds asks
    /// the same question where it decides what follows what: a pane with an open
    /// bar is following a match, so it must not be dragged back to the tail by
    /// the next batch — and a match the fresh lines have just moved has to be
    /// repainted, which is what <see cref="ConsoleFindTick"/> is for.</summary>
    bool ConsoleFindHolds(ConsolePane pane) =>
        _consoleFind.Any(b => b.Open && ReferenceEquals(b.Pane, pane));

    void OpenConsoleFind(ConsoleFindBar? bar)
    {
        bar ??= _findTarget ?? _consoleFind.FirstOrDefault();
        if (bar is null)
            return;

        _findTarget = bar;
        bar.Open = true;
        bar.Bar.IsVisible = true;

        // A find bar needs the console reading, because its count follows the
        // pane's revision (Windows starts the same timer here).
        StartConsoleTimer();

        var seed = bar.Pane.SelectedText;
        if (seed.Length > 0)
            bar.Input.Text = seed;

        bar.Input.Focus();
        bar.Input.SelectAll();
        RebuildConsoleFind(bar, jump: true);
    }

    void CloseConsoleFind(ConsoleFindBar bar)
    {
        // Closing forgets the search as well as the paint: nothing should be
        // highlighted after Escape, and the next Ctrl+F starts clean. This goes
        // through a rebuild with an empty query rather than ResetFind, because
        // ResetFind is the pane's own reset (a cleared pane, whose player keeps
        // wanting what they typed) and this one is the player's.
        Vm.RebuildFind(bar.Role, "", false, 0);
        bar.Pane.ClearFindMatch();
        bar.Open = false;
        bar.Bar.IsVisible = false;
        bar.Counter.Text = "";
        bar.Input.Text = "";
        bar.Pane.Focus();
    }

    /// <summary>
    /// Windows' ConsoleFindTick: every fourth tick of the console timer, an open
    /// bar whose pane has taken lines re-finds — four ticks is about a second of
    /// streaming output, which is how long a count can be stale before a player
    /// notices. Internal because the suite has no message loop to tick the timer
    /// for it, and calls this where a real window would.
    ///
    /// A rebuild here follows the pane: while the pane is following its tail the
    /// current match is the newest one, so the highlight goes with it; a player
    /// who has scrolled away keeps the highlight and only the count moves.
    /// </summary>
    internal void ConsoleFindTick()
    {
        Console.Error.WriteLine($"[find] tick n={_findTick + 1} stack={Environment.StackTrace.Split('\n')[2].Trim()}");
        if (++_findTick % 4 != 0)
            return;

        foreach (var bar in _consoleFind)
        {
            if (bar.Open && Vm.FindQuery(bar.Role).Length > 0)
                RebuildConsoleFind(bar, jump: bar.Pane.Follow);
        }
    }

    void RebuildConsoleFind(ConsoleFindBar bar, bool jump)
    {
        var view = Vm.RebuildFind(bar.Role, bar.Input.Text ?? "",
            bar.CaseToggle.IsChecked == true, bar.Anchor(Vm));
        ApplyFindView(bar, view, jump);
    }

    void StepConsoleFind(ConsoleFindBar bar, int delta)
    {
        if (!bar.Open)
            return;

        var view = Vm.StepFind(bar.Role, delta, bar.Anchor(Vm));
        ApplyFindView(bar, view, jump: true);
    }

    void ApplyFindView(ConsoleFindBar bar, ConsoleFindView view, bool jump)
    {
        bar.Counter.Text = view.Counter;
        if (jump && view.HasMatch)
            bar.Pane.ShowFindMatch(view.Match);
        else if (!view.HasMatch)
            bar.Pane.ClearFindMatch();
    }

    void OnConsoleFind(object? sender, RoutedEventArgs e) => OpenConsoleFind(null);

    private void OnConsoleFindClose(object? sender, RoutedEventArgs e)
    {
        if (FindBarOf(sender) is { } bar)
            CloseConsoleFind(bar);
    }

    private void OnConsoleFindPrev(object? sender, RoutedEventArgs e)
    {
        if (FindBarOf(sender) is { } bar)
            StepConsoleFind(bar, -1);
    }

    private void OnConsoleFindNext(object? sender, RoutedEventArgs e)
    {
        if (FindBarOf(sender) is { } bar)
            StepConsoleFind(bar, 1);
    }

    private void OnConsoleFindCaseChanged(object? sender, RoutedEventArgs e)
    {
        if (FindBarOf(sender) is { Open: true } bar)
            RebuildConsoleFind(bar, jump: true);
    }

    private void OnConsoleFindTextChanged(object? sender, TextChangedEventArgs e)
    {
        if (FindBarOf(sender) is not { } bar)
            return;

        // Closing a bar empties its box, and that is not a query.
        if (!bar.Open)
        {
            if (ReferenceEquals(_findPendingQuery, bar))
            {
                _findPendingQuery = null;
                _findDebounce?.Stop();
            }
            return;
        }

        // A query typed in one bar flushes the other: the debounce holds one
        // pending query, exactly as Windows' does.
        if (_findPendingQuery is not null && !ReferenceEquals(_findPendingQuery, bar))
            RebuildConsoleFind(_findPendingQuery, jump: true);

        _findPendingQuery = bar;
        _findDebounce?.Stop();
        _findDebounce?.Start();
    }

    private void OnConsoleFindKeyDown(object? sender, KeyEventArgs e)
    {
        if (FindBarOf(sender) is not { } bar)
            return;

        switch (e.Key)
        {
            case Key.Enter:
            {
                // Enter on a query the debounce has not run yet searches first —
                // the rebuild already lands on the match nearest the anchor, so
                // stepping here as well would skip it. Enter again steps.
                var pending = ReferenceEquals(_findPendingQuery, bar);
                FlushConsoleFindQuery(bar);
                if (!pending)
                    StepConsoleFind(bar, e.KeyModifiers.HasFlag(KeyModifiers.Shift) ? -1 : 1);
                e.Handled = true;
                break;
            }

            case Key.Escape:
                CloseConsoleFind(bar);
                e.Handled = true;
                break;
        }
    }

    /// <summary>
    /// Run the query the debounce has not run yet, and show its match: this is
    /// what Enter does, so it paints — a player who pressed the key is asking to
    /// be taken there, unlike the debounce, which only counts.
    /// </summary>
    void FlushConsoleFindQuery(ConsoleFindBar bar)
    {
        if (!ReferenceEquals(_findPendingQuery, bar))
            return;
        _findPendingQuery = null;
        _findDebounce?.Stop();
        RebuildConsoleFind(bar, jump: true);
    }

    /// <summary>
    /// Windows' MaybeOpenConsoleForLaunch: bring the Console tab forward after a
    /// launch, if the player asked for that in Settings.
    /// </summary>
    void MaybeOpenConsoleForLaunch()
    {
        if (Vm.OpenConsoleOnLaunch)
            SetSimpleTab(BtnTabConsole, PanelSimpleConsole);
    }

    void StartConsoleTimer()
    {
        if (_consoleTimer is { IsEnabled: false })
            _consoleTimer.Start();
    }

    /// <summary>Enter sends, Up/Down walk the command history — the same keys
    /// the Windows console box handles, with the history kept in the settings
    /// file so it survives a restart.</summary>
    private void OnConsoleServerCmdKeyDown(object? sender, KeyEventArgs e) =>
        HandleConsoleCmdKey(e, LaunchRole.Dedicated);

    private void OnConsoleClientCmdKeyDown(object? sender, KeyEventArgs e) =>
        HandleConsoleCmdKey(e, LaunchRole.Client);

    void HandleConsoleCmdKey(KeyEventArgs e, LaunchRole role)
    {
        var box = role == LaunchRole.Dedicated ? TxtConsoleServerCmd : TxtConsoleClientCmd;
        var history = Vm.HistoryFor(role);
        var nav = role == LaunchRole.Dedicated ? _historyNavServer : _historyNavClient;

        switch (e.Key)
        {
            case Key.Enter:
                var line = (box.Text ?? "").Trim();
                if (role == LaunchRole.Dedicated)
                    Vm.SubmitServerCommand(line);
                else
                    Vm.SubmitClientCommand(line);
                nav.Index = -1;
                nav.Draft = "";
                box.Text = "";
                e.Handled = true;
                break;

            case Key.Up:
                if (history.Count == 0)
                    return;
                if (nav.Index < 0)
                {
                    nav.Draft = box.Text ?? "";
                    nav.Index = history.Count - 1;
                }
                else if (nav.Index > 0)
                {
                    nav.Index--;
                }
                box.Text = history[nav.Index];
                box.CaretIndex = box.Text.Length;
                e.Handled = true;
                break;

            case Key.Down:
                if (nav.Index < 0)
                    return;
                nav.Index++;
                if (nav.Index >= history.Count)
                {
                    nav.Index = -1;
                    box.Text = nav.Draft;
                }
                else
                {
                    box.Text = history[nav.Index];
                }
                box.CaretIndex = box.Text.Length;
                e.Handled = true;
                break;
        }
    }

    /// <summary>Up/Down walk position and the in-progress line it returns to.
    /// Windows keeps one of these per pane.</summary>
    sealed class ConsoleHistoryNav
    {
        public int Index = -1;
        public string Draft = "";
    }

    /// <summary>Windows' OnReloadLevel: send the live playlist+map back through
    /// the changelevel path — how you restart the level you are on.</summary>
    private void OnReloadLevel(object? sender, RoutedEventArgs e)
    {
        PanelMapPicker.IsVisible = false;
        Vm.ReloadLevelCommand.Execute(null);
    }

    // ------------------------------------------------------------- settings

    private async void OnBrowseInstall(object? sender, RoutedEventArgs e) => await PickInstallFolder();
    private async void OnBrowseSimpleInstall(object? sender, RoutedEventArgs e) => await PickInstallFolder();

    private async System.Threading.Tasks.Task PickInstallFolder()
    {
        var folders = await StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
        {
            Title = "Choose the game install folder (the one holding r5apex.exe)",
            AllowMultiple = false,
        });
        if (folders.Count > 0)
        {
            Vm.InstallPath = folders[0].Path.LocalPath;
            Vm.AppendLog($"Install folder set to {Vm.InstallPath}");
            AttachInstallGate();
        }
    }

    private void OnResetInstallPath(object? sender, RoutedEventArgs e)
    {
        Vm.InstallPath = LinuxSettings.DefaultInstallPath();
        Vm.AppendLog($"Install folder reset to {Vm.InstallPath}");
        AttachInstallGate();
    }

    private void OnOpenInstall(object? sender, RoutedEventArgs e) =>
        Vm.OpenFolder(System.IO.Directory.Exists(Vm.InstallPath) ? Vm.InstallPath : Vm.PrefixPath);

    private void OnUiLanguageChanged(object? sender, SelectionChangedEventArgs e)
    {
        if (sender is ComboBox { SelectedItem: LanguageRow row } && !ReferenceEquals(row, Vm.SelectedLanguage))
            Vm.SetLanguageCommand.Execute(row);
    }

    // ------------------------------------------------------------- credits

    private void OnCreditRowClick(object? sender, Avalonia.Input.TappedEventArgs e)
    {
        if (sender is Control { DataContext: CreditEntryVM entry })
            Vm.OpenUrl(entry.Url);
    }

    // ---------------------------------------------------------- footer links

    private void OnOpenWebsite(object? sender, RoutedEventArgs e) => Vm.OpenUrl(MainViewModel.WebsiteUrl);

    /// <summary>Opens the standalone server package page. The link is only visible
    /// while the master server says it is publishing that package.</summary>
    private void OnOpenDediPackage(object? sender, RoutedEventArgs e) =>
        Vm.OpenUrl(MainViewModel.DediPackageUrl);
    private void OnOpenDiscord(object? sender, RoutedEventArgs e) => Vm.OpenUrl(MainViewModel.DiscordUrl);
    private void OnOpenGitHub(object? sender, RoutedEventArgs e) => Vm.OpenUrl(MainViewModel.GitHubUrl);
    private void OnOpenPatreon(object? sender, RoutedEventArgs e) => Vm.OpenUrl(MainViewModel.PatreonUrl);
    private void OnOpenKofi(object? sender, RoutedEventArgs e) => Vm.OpenUrl(MainViewModel.KofiUrl);
    private void OnOpenToolsRepos(object? sender, RoutedEventArgs e) => Vm.OpenUrl(MainViewModel.ToolsUrl);
    /// <summary>Read-only view of the same notice — no Accept/Decline, no gate.</summary>
    private async void OnReadEula(object? sender, RoutedEventArgs e)
    {
        var url = CurrentMasterServerUrl();
        var fetched = await NoticeClient.GetEulaAsync(url, Vm.EulaUiLanguage());
        var dlg = new EulaWindow(this, url, requireAccept: false,
            prefetched: fetched.Success ? fetched : null, vm: Vm);
        await dlg.ShowDialog<bool>(this);
    }
}

file static class ClassExtensions
{
    public static void Set(this Classes classes, bool on)
    {
        if (on) classes.Add("on");
        else classes.Remove("on");
    }
}